# This file was generated by GoReleaser. DO NOT EDIT.
cask "zigflow" do
  version "0.14.3"

  on_macos do
    on_intel do
      sha256 "deb33e59c43bf1c90065e4baecbe4ab4edee02a599492343ffc5c4bef5a7251b"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_darwin_x86_64"
      binary "zigflow_darwin_x86_64", target: "zigflow"
    end
    on_arm do
      sha256 "a5061deb29e80663a3ab7b494e1743cb655543cbe91c2d327376842939cc7205"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_darwin_arm64"
      binary "zigflow_darwin_arm64", target: "zigflow"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d5bf4cf2d72d34a25ea56a3fea216d8dca9716bc8a71969c2449c3c1f2cdee6"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_linux_x86_64"
      binary "zigflow_linux_x86_64", target: "zigflow"
    end
    on_arm do
      sha256 "4c3e0e608e2c1b93c215519821020519940ab2b104552481d82187076a10c31e"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_linux_arm64"
      binary "zigflow_linux_arm64", target: "zigflow"
    end
  end

  name "zigflow"
  desc "Define durable workflows in YAML, powered by Temporal"
  homepage "https://zigflow.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary_name = if Hardware::CPU.intel?
        "zigflow_darwin_x86_64"
      else
        "zigflow_darwin_arm64"
      end

      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installs the latest stable Zigflow release.

    For a specific version, use GitHub Releases or Docker.
  EOS
end
