# This file was generated by GoReleaser. DO NOT EDIT.
cask "zigflow" do
  version "0.12.1"

  on_macos do
    on_intel do
      sha256 "c33bb3cefc64c7ce4d8e94747c449b9725d740985223db056f36787ed922dc83"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_darwin_x86_64"
      binary "zigflow_darwin_x86_64", target: "zigflow"
    end
    on_arm do
      sha256 "d63d849ad86e4239ef100d63b4caca08375397c3d86bc08eb8b42bc914d6c9b7"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_darwin_arm64"
      binary "zigflow_darwin_arm64", target: "zigflow"
    end
  end

  on_linux do
    on_intel do
      sha256 "a95c1160157f50ec51845f0adadbfd68197101fbd606e41de5802e7646634078"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_linux_x86_64"
      binary "zigflow_linux_x86_64", target: "zigflow"
    end
    on_arm do
      sha256 "11682610d6e1db5dc17fd30f24c5d2c2c840a162095108e0eac7249ccead4cc1"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_linux_arm64"
      binary "zigflow_linux_arm64", target: "zigflow"
    end
  end

  name "zigflow"
  desc "Define durable workflows in YAML, powered by Temporal"
  homepage "https://zigflow.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary_name = if Hardware::CPU.intel?
        "zigflow_darwin_x86_64"
      else
        "zigflow_darwin_arm64"
      end

      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installs the latest stable Zigflow release.

    For a specific version, use GitHub Releases or Docker.
  EOS
end
