# This file was generated by GoReleaser. DO NOT EDIT.
cask "zigflow" do
  version "0.12.1"

  on_macos do
    on_intel do
      sha256 "64e582635833d865ef99565b5dff5f3b829dc05357d0d863c1b0a517c93c15e3"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_darwin_x86_64"
      binary "zigflow_darwin_x86_64", target: "zigflow"
    end
    on_arm do
      sha256 "88211cb720876370b6560cf2d86d08d73ee57217930aed6c5b0b1f76966dfad3"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_darwin_arm64"
      binary "zigflow_darwin_arm64", target: "zigflow"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4fa4ec4ab0cc0cd2ec9bb4fcadba3420622cf90f2b1c2fe4d5364ea43f7e311"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_linux_x86_64"
      binary "zigflow_linux_x86_64", target: "zigflow"
    end
    on_arm do
      sha256 "c6870b40e4c0de1eb13df62a81421d3deac83c2e9fea3626abe683e390f15f61"
      url "https://github.com/zigflow/zigflow/releases/download/v#{version}/zigflow_linux_arm64"
      binary "zigflow_linux_arm64", target: "zigflow"
    end
  end

  name "zigflow"
  desc "Define durable workflows in YAML, powered by Temporal"
  homepage "https://zigflow.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary_name = if Hardware::CPU.intel?
        "zigflow_darwin_x86_64"
      else
        "zigflow_darwin_arm64"
      end

      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installs the latest stable Zigflow release.

    For a specific version, use GitHub Releases or Docker.
  EOS
end
